# lista = [1,6,6,10,89,4]
# print(len(lista))
#  verificar o tamanho da minha lista 
#  -------------------------------------
# adiciono um valor dentro da lista 
# lista.append (10)
#  acessar um indice e atribuir um no 
# lista [0] = 2
# print (lista)

# --------------------------------------

# remover o valor da lista pelo indi
# del lista[0] = 2
# print (lista)

# --------------------------------------

#  remover o valor da lista pelo indice(index)
# del lista[0] # vai re
# print(lista)
#  vai remover pelo valor(value)
# lista.remove(89)
# print(lista)

#  -------------------------------

#  iterar é percorer uma lista
# lista2 = [2,1,0]
# loop -> repetindo
# senha = 132
# for numero in range(-3,0):
#     minha_senha = int(input('Digite a senha: '))
#     if senha  == minha_senha:
#        print('acesso liberado')

#     else: 
#         print('acesso negado') 
#         print('Você tem apenas', numero ,'chances para digitar a senha'        )   

     
  


# for index in range(1,10):
#     nome = input('Digite seu nome')
#     print('Seja bem vindo(a)', nome, index)

#  loop repetição 
# for index in range(1,11):
#     print('numero:', index)


# lista = [1,2,3,4,5]
# for pessoa in range(1,6):
#     n = 10
#     x = 20
#     print('Pessoa', pessoa, n + x)    




1

 lista = []

 while  len(lista)=+1 <=5:
     lista.append(int(input("digite número")
 print("o maior numero é: ")

#2
# numeros = [1,2,3,4,5]
# print(numero[2])

#3

# numeros.append(9)
# print(numero)

 




#5

# carros = ['ferrari', 'golf', 'jetta']
# concatene = carros + numeros 
# print(concatene)






# 7

# if 5 in numeros:
#     print('existe')
# else:
#     print('não existe')
